spring.application.name=ClickToCodeBot
# Server port
server.port=8080

# Spring datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ClickToCodeBot
spring.datasource.username=ClickToCodeBot
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Telegram Bot Configuration
telegram.bot.token=7994660955:AAGThTRDVU_At1hxDZhFjmcUroUDhi5i0xk
telegram.bot.username=@ClickToCodeBot_bot

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.yourcompany=DEBUG

# Admin credentials (optional, can be changed to secure authentication method)
#admin.username=admin
#admin.password=your_admin_password

# Security settings (optional, if you have JWT or session-based authentication)
#spring.security.user.name=admin
#spring.security.user.password=admin_password

# Time zone and Locale settings for Uzbekistan
spring.jackson.time-zone=Asia/Tashkent
spring.jackson.locale=uz_UZ